DROP TABLE AGENT;
DROP TABLE LOCATAIRE;
DROP TABLE PROPRIETAIRE;

/*drop en cascade de logement manuelle*/

DROP TABLE LOCATION;
DROP TABLE VENTE;
DROP SEQUENCE SEQ_agent_agent_;
DROP SEQUENCE SEQ_LOCATAIRE_LOCATAIRE;
DROP SEQUENCE SEQ_LOCATION_LOCATION_;
DROP SEQUENCE SEQ_LOGEMENT_LOGEMENT_;
DROP SEQUENCE SEQ_proprietaire_proprietaire_;
DROP SEQUENCE SEQ_vente_vente_;
